# Generated by Django 3.1 on 2022-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='image',
            field=models.ImageField(null=True, upload_to='private/images/'),
        ),
    ]
